name: Add Word

on:
  workflow_dispatch:
    inputs:
      word:
        description: "The new word to add"
        required: true
        type: string

permissions:
  contents: write

jobs:
  add-word:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Append word to words.txt
        run: |
          echo "${{ github.event.inputs.word }} ($(date -u +'%Y-%m-%dT%H:%M:%SZ'))" >> words.txt

      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add words.txt
          git commit -m "Add word: ${{ github.event.inputs.word }}"
          git push
