name: Deploy Hugo site to Pages

on:
  push:
    branches:
      - main  # when you push changes to main branch

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - uses: actions/checkout@v4

      # 2. Setup Hugo
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      # 3. Inject GitHub Token into site
      - name: Inject GitHub Token into site
        run: |
          mkdir -p ./assets/js
          echo "window.GITHUB_TOKEN='${{ secrets.GH_PAT }}'" > ./assets/js/token.js

      # 4. Build Hugo site
      - name: Build
        run: hugo --minify

      # 5. Deploy to GitHub Pages branch
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
